import { CreateUserForm, LukkerUserInfo } from "../reducers/potlukk-reducer";

// Generated by https://quicktype.io

export type ValidationError = {
    detail: Detail[];
}

export type Detail = {
    loc:  Array<number | string>;
    msg:  string;
    type: string;
}

export type VerifySignin = {
    username: string;
    password: string;
}

export async function createUser(params:CreateUserForm):Promise<LukkerUserInfo> {
    const httpResponse = await fetch("http://127.0.0.1:8000/lukkers", {
        method:"POST",
        body:JSON.stringify(params),
        headers:{"Content-Type":"application/json"}
    });
    const newUser = await httpResponse.json();
    return newUser;
}

export async function getAllUsers():Promise<LukkerUserInfo[]>{
    const httpResponse = await fetch("http://127.0.0.1:8000/lukkers", {
        method:"Get",
        headers:{"Content-Type":"application/json"}
    });
    const newUser:LukkerUserInfo[] = await httpResponse.json();
    return newUser;
}

export async function getUserById(params:string):Promise<LukkerUserInfo>{
    const httpResponse = await fetch("http://127.0.0.1:8000/lukkers/"+params, {
        method:"Get",
        headers:{"Content-Type":"application/json"}
    });
    const newUser:LukkerUserInfo = await httpResponse.json();
    return newUser;
}

